name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run microtests
        run: ./gradlew testDebug

      - name: Debug Info
        run: |
          echo "Java version:"
          java -version
          echo "Gradle version:"
          ./gradlew --version
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
